version: '3.8'

services:
  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:Gar7a28001082@34.122.253.242:3306/website_builder
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=10web-clone-2024-secret-key-xyz123-abc456
      - WP_CLI_PATH=/usr/local/bin/wp
      - WORDPRESS_INSTALL_DIR=/var/www/wordpress
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  # WordPress installation
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=34.122.253.242
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=Gar7a28001082
      - WORDPRESS_DB_NAME=website_builder
    volumes:
      - wordpress_data:/var/www/html

  # WP-CLI for automation
  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
    environment:
      - WORDPRESS_DB_HOST=34.122.253.242
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=Gar7a28001082
      - WORDPRESS_DB_NAME=website_builder
    volumes:
      - wordpress_data:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["tail", "-f", "/dev/null"] # keep container running for exec

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=34.122.253.242
      - PMA_USER=root
      - PMA_PASSWORD=Gar7a28001082
    depends_on:
      - wordpress

volumes:
  wordpress_data: 