# Google Cloud configuration for the platform
version: '3.8'

services:
  app:
    build: .
    image: gcr.io/${PROJECT_ID}/business-website-builder
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
      - NEXT_PUBLIC_API_URL=${API_URL}
    ports:
      - "8080:8080"
    resources:
      limits:
        cpus: '1'
        memory: 1G
      reservations:
        cpus: '0.5'
        memory: 512M
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == worker

  database:
    image: gcr.io/cloudsql-docker/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  mysql-data:
  redis-data: 